createEmployeeForm:
  path: /employee/create
  controller: App\Controller\EmployeeController::createEmployee

employeeList:
  path: /{page}
  controller: App\Controller\EmployeeController::employeeList
  defaults:
    page: 1
  requirements:
    page: '\d+'

employeeShow:
  path: /employee/{id}
  controller: App\Controller\EmployeeController::employeeShow
  defaults:
    page: 1
  requirements:
    id: '\d+'
